on: [push, pull_request]

name: R-linux
  
jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-latest, r: 'release', args: "--no-manual"}
        - {os: macOS-latest, r: 'release', args: "--no-manual"}
        - {os: ubuntu-latest, r: 'release', http-user-agent: 'release', args: "--no-manual"}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      GITHUB_PAT: ${{secrets.GH_PAT}}
      
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-tinytex@master
        if: contains(matrix.config.args, 'no-manual') == false

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
                  
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: runner.os == 'macos-latest'
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        if: runner.os == 'macos-latest'
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

      - name: Install package
        if: runner.os == 'macos-latest'
        run: R CMD INSTALL .

      - name: covrpage
        if: runner.os == 'macos-latest'      
        if: github.ref == 'refs/heads/master'
        run: |
          Rscript -e 'remotes::install_github("yonicd/covrpage@actions")' \
                  -e 'covrpage::covrpage_ci()'
          git commit tests/README.md -m 'Update tests/README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: runner.os == 'macos-latest'
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        if: runner.os == 'macos-latest'      
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: runner.os == 'macos-latest'              
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
